# Generated by Django 5.2.1 on 2025-05-20 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store'),
            preserve_default=False,
        ),
    ]
